services:
  - type: web
    name:   neurolearn-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python start_server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: neurolearn-db
          property: connectionString
      - key: PORT
        value: $PORT
    healthCheckPath: /api/auth/health
    autoDeploy: true
    branch: main

databases:
  - name: neurolearn-db
    plan: starter
    databaseName: neurolearn
    user: neurolearn_user
